blog:
  image: abesto/blog
  volumes:
    - $NGINX_LOGDIR:/var/log/nginx

mastermind:
  image: abesto/mastermind
  volumes:
    - $NGINX_LOGDIR:/var/log/nginx

boardredis:
  image: dockerfile/redis
  volumes:
    - $REDIS_STORE/are-you-board:/data
  command: redis-server --appendonly yes
board:
  image: abesto/are-you-board
  links:
    - boardredis:redis

algo:
  image: abesto/algo

lycheedata:
  image: busybox
  volumes:
    - $LYCHEE_DATA:/data/
    - $LYCHEE_UPLOADS:/uploads/
    - /var/lib/mysql/
lychee:
  image: kdelfour/lychee-docker
  volumes_from:
    - lycheedata

static:
  image: dockerfile/nginx
  volumes:
    - $STATIC_DATA:/var/www/html
    - $NGINX_LOGDIR:/var/log/nginx

haproxy:
  image: dockerfile/haproxy
  ports:
    - "80:80"
  volumes:
    - haproxy:/haproxy-override
  links:
    - blog
    - mastermind
    - algo
    - board:are-you-board
    - lychee
    - static
