##############
# abesto.net #
##############
blog:
  image: abesto/blog:latest
  volumes:
    - $NGINX_LOGDIR:/var/log/nginx
  restart: always

#########################
# mastermind.abesto.net #
#########################
mastermind:
  image: abesto/mastermind:latest
  volumes:
    - $NGINX_LOGDIR:/var/log/nginx
  restart: always

####################
# board.abesto.net #
####################
boardredis:
  image: redis:latest
  volumes:
    - $REDIS_STORE/are-you-board:/data
  command: redis-server --appendonly yes
  restart: always

board:
  image: abesto/are-you-board:latest
  links:
    - boardredis:redis

###################
# algo.abesto.net #
###################
algo:
  image: abesto/algo:latest

#####################
# lychee.abesto.net #
#####################
lycheedata:
  image: kdelfour/lychee-docker:latest
  volumes:
    - $LYCHEE_DATADIR:/data/
    - $LYCHEE_UPLOADS:/uploads/
    - $LYCHEE_MYSQL:/var/lib/mysql
  command: /bin/true

lychee:
  image: kdelfour/lychee-docker:latest
  volumes_from:
    - lycheedata

#######################
# static.abesto.net   #
# releases.abesto.net #
#######################
static:
  image: nginx:latest
  volumes:
    - $STATIC_DATA:/var/www/html
    - $NGINX_LOGDIR:/var/log/nginx
    - static/etc/nginx/conf.d:/etc/nginx/conf.d

# Pull it all together
haproxy:
  image: haproxy:latest
  ports:
    - "80:80"
  volumes:
    - haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    - haproxy/unknown-domain.html:/usr/local/etc/haproxy/unknown-domain.html:ro
  links:
    - blog
    - mastermind
    - algo
    - board
    - lychee
    - static
